name: Auto message on Creating Issue.

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Create comment for issue
        if: github.event_name =='issues'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{tojson(github.event.issue.number)}}
          body: |
            Hi 😄, @${{ github.actor }} Thanks for creating an issue at Vita.
            To get assigned to this particular issue please use <b>/assign</b><br>
